// READ-EM-DASH-01 — the gate for the runtime half of the em-dash rule.
//
// ⚠️ BEHAVIOURAL, NOT SOURCE-SHAPED, AND DELIBERATELY SO. Both existing em-dash
// guards scan source text, which is the right shape for copy a human typed and the
// WRONG shape for copy a model writes in production. These arms call the real
// functions and read their real output, so a producer that regains an em dash fails
// here whether the mark was typed by a person or generated by a model.
import { describe, it, expect } from 'vitest'
import { withoutEmDashes, containsEmDash, EN_DASH } from './runnerProse'
import { manualFeedbackText, manualMetricsFeedbackText } from './manualSessionFeedback'
import { buildVoiceHeader } from './prompts/voiceRules'
import { readBudgetInstruction } from './readBudget'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const EM = '—'

describe('withoutEmDashes', () => {
  it('replaces a parenthetical em dash with a comma', () => {
    expect(withoutEmDashes(`HR ran warm ${EM} 28C will do that`))
      .toBe('HR ran warm, 28C will do that')
  })

  it('handles the real production read verbatim', () => {
    // The founder's own row, 2026-10-07T13:45, quoted from `feedback_text`.
    const live = `HR ran 13 beats hot the whole way ${EM} that's not an easy run.`
    const out = withoutEmDashes(live)
    expect(out).toBe("HR ran 13 beats hot the whole way, that's not an easy run.")
    expect(containsEmDash(out)).toBe(false)
  })

  it('handles two em dashes in one sentence', () => {
    const out = withoutEmDashes(`HR ran warm ${EM} 28C will do that ${EM} but the limiter is muscular.`)
    expect(out).toBe('HR ran warm, 28C will do that, but the limiter is muscular.')
  })

  it('does not double punctuation when the dash follows a full stop', () => {
    expect(withoutEmDashes(`Good run. ${EM} but ease off tomorrow.`))
      .toBe('Good run. but ease off tomorrow.')
  })

  it('drops a dangling dash at either end', () => {
    expect(withoutEmDashes(`${EM} and that was that`)).toBe('and that was that')
    expect(withoutEmDashes(`and that was that ${EM}`)).toBe('and that was that')
  })

  it('handles an unspaced em dash', () => {
    expect(withoutEmDashes(`5km${EM}right on the number.`)).toBe('5km, right on the number.')
  })

  // 🔴 THE FALSIFICATION THAT MATTERS. A transform that reached U+2013 would corrupt
  // every pace band and zone range in the product, and the two marks are one
  // keystroke apart. `CLAUDE.md`: en dashes in ranges "are correct and must be kept".
  it('NEVER touches an en dash in a range', () => {
    const ranges = `Target ${6}:30${EN_DASH}7:30 /km in Zone 4${EN_DASH}5 at RPE 1${EN_DASH}10.`
    expect(withoutEmDashes(ranges)).toBe(ranges)
  })

  it('leaves an en-dash range intact while removing an em dash beside it', () => {
    const out = withoutEmDashes(`Zone 4${EN_DASH}5 was the target ${EM} you sat under it.`)
    expect(out).toBe(`Zone 4${EN_DASH}5 was the target, you sat under it.`)
    expect(out).toContain(EN_DASH)
  })

  it('is idempotent and returns clean text unchanged by identity', () => {
    const clean = 'HR sat right in Zone 2 the whole way. That is the discipline.'
    expect(withoutEmDashes(clean)).toBe(clean)
    expect(withoutEmDashes(withoutEmDashes(`a ${EM} b`))).toBe('a, b')
  })
})

// The SECOND producer. These are our own template literals, fixed at source rather
// than wrapped, because the source is ours and should simply be right. The arms
// exist so it stays right: `manualSessionFeedback.ts` sits in `lib/coaching/`, which
// `noEmDashApp.test.ts` cannot see and must not be made to see — `BRAND-EMDASH-LIB-01`
// ruled that adding `lib/` to its roots would fire on 250 literals, most of which no
// runner reads, "and a guard that fires on ordinary work gets switched off".
//
// ⚠️ SO THIS GUARD IS SCOPED BY WHERE THE STRINGS SURFACE, NOT BY WHERE THEY LIVE,
// which is the fix `BRAND-EMDASH-LIB-01` itself asks for. Every branch is walked, so
// the population is the function's real output and not a sample of it.
describe('manual feedback text carries no em dash (the rule-engine producer)', () => {
  const TYPES = ['easy', 'recovery', 'run', 'long', 'quality', 'intervals', 'tempo', 'hard', 'race', 'strength']
  const TAGS  = ['Fresh', 'Fine', 'Heavy', 'Wrecked', null]

  it('manualFeedbackText: every type x rpe x fatigue branch', () => {
    const offenders: string[] = []
    let n = 0
    for (const t of TYPES) {
      for (const rpe of [null, 1, 3, 5, 7, 9, 10]) {
        for (const tag of TAGS) {
          const out = manualFeedbackText(t, rpe, tag)
          n++
          if (containsEmDash(out)) offenders.push(`${t}/${rpe}/${tag}: ${out}`)
        }
      }
    }
    expect(n).toBeGreaterThan(300)
    expect(offenders).toEqual([])
  })

  it('manualMetricsFeedbackText: every HR and distance branch, both unit systems', () => {
    const offenders: string[] = []
    let n = 0
    for (const units of ['km', 'mi'] as const) {
      for (const t of TYPES) {
        // HR-led branches: inside the band, a touch over, way over, and under.
        for (const avgHr of [130, 145, 150, 160, 175]) {
          const out = manualMetricsFeedbackText(t, { distanceKm: 8, plannedKm: 8, avgHr, hrCeiling: 150 }, units)
          n++
          if (containsEmDash(out)) offenders.push(`hr ${t}/${avgHr}/${units}: ${out}`)
        }
        // Distance-led branches: on the number, short, long, and no plan at all.
        for (const [distanceKm, plannedKm] of [[8, 8], [6, 8], [10, 8], [8, null]] as [number, number | null][]) {
          const out = manualMetricsFeedbackText(t, { distanceKm, plannedKm, avgHr: null, hrCeiling: null }, units)
          n++
          if (containsEmDash(out)) offenders.push(`dist ${t}/${distanceKm}v${plannedKm}/${units}: ${out}`)
        }
      }
    }
    expect(n).toBeGreaterThan(100)
    expect(offenders).toEqual([])
  })
})

// 🔴 THE ARM THAT EXPLAINS WHY THE RULE WAS FAILING, and the one most worth keeping.
//
// READ-EM-DASH-01 was filed stating "the prompt does not forbid it either". IT DID.
// `buildVoiceHeader` has carried `- Never use an em dash. Use a colon, comma,
// semicolon or full stop.` since BRAND-EMDASH-APP-01, and it reaches all fourteen
// model surfaces. So the stated instruction was live the whole time the model was
// producing em dashes in 18% of live reads.
//
// ⚠️ WHAT THE INSTRUCTION WAS COMPETING WITH WAS ITSELF. The same header used FOUR
// em dashes in its own text, one in the sentence directly above the rule and one
// inside a worked example of good style ("Reach for observational stems — ... —
// when the data warrants"). A model mimics demonstrated style over stated rules, so
// the header asked for one thing and showed another on the same page.
//
// That is the same shape as the instance BRAND-EMDASH-APP-01 already recorded
// ("contradicted by that prompt's own worked example two hundred lines above it") —
// it fixed the copy in one prompt and left the ones in the SHARED OWNER, which every
// prompt inherits. These arms make the owner prove it, so the next sentence added to
// the voice header cannot reintroduce the contradiction.
describe('the prompt does not demonstrate what it forbids', () => {
  const ROLES = ['giving session feedback', 'writing a weekly check-in', 'reviewing a race']

  it('buildVoiceHeader carries the rule', () => {
    expect(buildVoiceHeader({ role: ROLES[0], units: 'km' })).toContain('Never use an em dash')
  })

  it('buildVoiceHeader never contains an em dash, across its option matrix', () => {
    const offenders: string[] = []
    for (const role of ROLES) {
      for (const units of ['km', 'mi'] as const) {
        for (const includeVoiceAnchor of [true, false]) {
          for (const firstName of ['Russ', undefined]) {
            for (const outputConstraint of [readBudgetInstruction(), undefined]) {
              const h = buildVoiceHeader({ role, units, includeVoiceAnchor, firstName, outputConstraint })
              if (containsEmDash(h)) {
                offenders.push(`${role}/${units}/anchor=${includeVoiceAnchor}/name=${firstName}: ` +
                  h.split('\n').filter(containsEmDash).join(' | '))
              }
            }
          }
        }
      }
    }
    expect(offenders).toEqual([])
  })

  // ⚠️ SOURCE-SHAPED, AND DECLARED AS SUCH. The only honest alternative would be to
  // invoke `/api/analyse-run`, which needs a bearer token, a tier lookup and a
  // service-role client — none of which stand up under `environment: 'node'`. Same
  // reasoning, and the same declaration, as `freeIngestLine.test.ts`.
  //
  // It asserts the WIRING, because the sanitiser being correct (proved above,
  // behaviourally) and the sanitiser being CALLED are different claims, and this
  // repo has shipped the first without the second more than once.
  it('the analyse-run boundary pipes model output through the sanitiser', () => {
    const src = readFileSync(join(process.cwd(), 'app/api/analyse-run/route.ts'), 'utf8')
    expect(src).toContain("from '@/lib/coaching/runnerProse'")
    expect(src).toMatch(/feedbackText\s*=\s*withoutEmDashes\(/)
  })

  it('readBudgetInstruction never contains an em dash', () => {
    // It is injected INTO the voice header as an output constraint, so it is the
    // same demonstrated-style problem one function further out.
    expect(containsEmDash(readBudgetInstruction())).toBe(false)
  })
})
