// AIMark — the canonical "this came from AI" glyph.
//
// Visual: 4-point sparkle + small accent dot top-right (Apple Intelligence-style).
// Used to mark Claude-generated content. Honest provenance — never decorative.
//
// Rules of use (see docs/canonical/ui-patterns.md § AIMark):
//   - Only on content generated by a model (run feedback, weekly report,
//     plan-enricher coach notes, etc.). NEVER on rule-engine output, session
//     catalogue templates, or hand-authored copy.
//   - Static state for rendered AI content.
//   - Working state (animated pulse) when AI is in flight — replaces the
//     spinner pattern banned by ui-patterns.md.
//
// Single source of truth. Don't reimplement the glyph anywhere else.

import React from 'react'

export interface AIMarkProps {
  /** Visual size in px. Defaults to 12 for inline eyebrow contexts. */
  size?: number
  /** Colour token or hex. Defaults to --moss; pass --warn for coach-amber surfaces. */
  color?: string
  /** Animated pulse — use while AI is generating. */
  working?: boolean
  /** Optional aria-label. Defaults to "AI generated" / "AI generating". */
  label?: string
}

export default function AIMark({
  size = 12,
  color = 'var(--moss)',
  working = false,
  label,
}: AIMarkProps) {
  const ariaLabel = label ?? (working ? 'AI generating' : 'AI generated')
  // viewBox scaled to give the accent dot some room top-right.
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 14 14"
      role="img"
      aria-label={ariaLabel}
      style={working ? { animation: 'ai-mark-pulse 1.6s ease-in-out infinite', transformOrigin: 'center' } : undefined}
    >
      {/* Main 4-point sparkle */}
      <path d="M5 1 L6 5 L10 6 L6 7 L5 11 L4 7 L0 6 L4 5 Z" fill={color} />
      {/* Smaller accent sparkle, top-right */}
      <path d="M11 9 L11.4 10.6 L13 11 L11.4 11.4 L11 13 L10.6 11.4 L9 11 L10.6 10.6 Z" fill={color} />
    </svg>
  )
}
