// CoachNoteBlock — Zona Phase 2 shared component
// Renders the coach voice card in amber-warm style.
// See docs/canonical/ui-patterns.md § CoachNoteBlock and docs/alignment/phase-2-decisions.md D-001.

import AIMark from './AIMark'

type Props = {
  /** Eyebrow label — default "COACH" */
  label?: string
  /** Optional timestamp shown in eyebrow row — e.g. "6:12am" */
  timestamp?: string
  /** The coaching copy. One sentence per brand voice rules. */
  children: React.ReactNode
  /**
   * 'why'  = "Why this session" variant for Session Detail.
   *          Slightly smaller body — label is the visual anchor.
   */
  variant?: 'default' | 'why'
  /** True when content was generated by a model (provenance honesty). Adds AIMark to eyebrow. */
  aiGenerated?: boolean
}

export default function CoachNoteBlock({
  label = 'COACH',
  timestamp,
  children,
  variant = 'default',
  aiGenerated = false,
}: Props) {
  const isWhy = variant === 'why'

  return (
    <div
      className="card-contextual"
      style={{
        background: 'var(--warn-bg)',
        borderRadius: '14px',
        padding: isWhy ? '14px 16px' : '16px 18px',
      }}
    >
      {/* Top row: eyebrow only — the label is the visual anchor */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          marginBottom: '10px',
        }}
      >
        {/* Eyebrow: "✦ COACH · 6:12am" — sparkle prepended when AI-generated */}
        <span
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '5px',
            fontFamily: 'var(--font-ui)',
            fontSize: '10px',
            fontWeight: 700,
            color: 'var(--warn)',
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            lineHeight: 1,
          }}
        >
          {aiGenerated && <AIMark size={10} color="var(--warn)" />}
          <span>
            {label}
            {timestamp && (
              <span style={{ fontWeight: 400, opacity: 0.65 }}>
                {' '}·{' '}{timestamp}
              </span>
            )}
          </span>
        </span>
      </div>

      {/* Body copy — warm dark brown on warm amber background */}
      <div
        style={{
          fontFamily: 'var(--font-ui)',
          fontSize: isWhy ? '13px' : '14px',
          fontWeight: 400,
          lineHeight: 1.55,
          color: 'var(--coach-ink)',
        }}
      >
        {children}
      </div>
    </div>
  )
}
