// CoachNoteBlock — Zona Phase 2 shared component
// Renders the coach voice card in amber-warm style.
// See docs/canonical/ui-patterns.md § CoachNoteBlock and docs/alignment/phase-2-decisions.md D-001.
//
// AI provenance signals (AI-VIS-01):
//   - When aiGenerated, the eyebrow shows a CoachByline (avatar + name + role).
//   - When aiGenerated, a 3px warn left-rail accents the card (Linear/Arc style).
//     Rule-engine notes get neither — provenance honesty.

import CoachByline from './CoachByline'

type Props = {
  /** Eyebrow label — default "COACH". Used only for non-AI notes. */
  label?: string
  /** Optional timestamp shown in eyebrow row — e.g. "6:12am" */
  timestamp?: string
  /** The coaching copy. One sentence per brand voice rules. */
  children: React.ReactNode
  /**
   * 'why'  = "Why this session" variant for Session Detail.
   *          Slightly smaller body — label is the visual anchor.
   */
  variant?: 'default' | 'why'
  /** True when content was generated by a model (provenance honesty). Renders the byline + rail. */
  aiGenerated?: boolean
  /**
   * When provided and aiGenerated is true, the byline becomes tappable.
   * Pass () => setScreen('coach') from the parent to navigate to the Coach tab.
   */
  onChipClick?: () => void
}

export default function CoachNoteBlock({
  label = 'COACH',
  timestamp,
  children,
  variant = 'default',
  aiGenerated = false,
  onChipClick,
}: Props) {
  const isWhy = variant === 'why'
  const horizontalPadding = isWhy ? 16 : 18
  const verticalPadding   = isWhy ? 14 : 16

  return (
    <div
      className="card-contextual"
      style={{
        position:     'relative',
        background:   'var(--warn-bg)',
        borderRadius: '14px',
        padding:      `${verticalPadding}px ${horizontalPadding}px ${verticalPadding}px ${aiGenerated ? horizontalPadding + 8 : horizontalPadding}px`,
      }}
    >
      {/* AI provenance left-rail — 3px warn accent for AI-generated notes only */}
      {aiGenerated && (
        <span
          aria-hidden="true"
          style={{
            position:     'absolute',
            left:         '8px',
            top:          `${verticalPadding}px`,
            bottom:       `${verticalPadding}px`,
            width:        '3px',
            borderRadius: '2px',
            background:   'var(--warn)',
          }}
        />
      )}

      {/* Top row: byline (AI) or eyebrow label (rule-engine) + optional timestamp */}
      <div
        style={{
          display:      'flex',
          alignItems:   'center',
          gap:          '8px',
          marginBottom: '10px',
        }}
      >
        {aiGenerated
          ? <CoachByline color="warn" onClick={onChipClick} />
          : (
            <span
              style={{
                fontFamily:    'var(--font-ui)',
                fontSize:      '10px',
                fontWeight:    700,
                color:         'var(--warn)',
                letterSpacing: '0.14em',
                textTransform: 'uppercase',
                lineHeight:    1,
              }}
            >
              {label}
            </span>
          )
        }
        {timestamp && (
          <span
            style={{
              fontFamily: 'var(--font-ui)',
              fontSize:   '10px',
              fontWeight: 400,
              color:      'var(--warn)',
              opacity:    0.65,
              lineHeight: 1,
            }}
          >
            · {timestamp}
          </span>
        )}
      </div>

      {/* Body copy — warm dark brown on warm amber background */}
      <div
        style={{
          fontFamily: 'var(--font-ui)',
          fontSize:   isWhy ? '13px' : '14px',
          fontWeight: 400,
          lineHeight: 1.55,
          color:      'var(--coach-ink)',
        }}
      >
        {children}
      </div>
    </div>
  )
}
