// CoachByline — the canonical AI-coach authorship signal.
//
// 22px Kit avatar (moss/warn gradient) + name + role line. AIMark sparkle is
// anchored to the avatar's bottom-right corner in a small white circle so the
// glyph is always identifiable at a glance, even while pulsing during generation.
//
// Replaces AICoachChip on every AI-generated surface. The 11px pill wasn't
// reading as authorship — it read as a category tag. The byline gives provenance
// a face (same trick Granola, Notion AI, and Superhuman use).
//
// Rules of use (see docs/canonical/ui-patterns.md § CoachByline):
//   - Only on content genuinely generated by a model (run feedback, weekly
//     report, daily coach note, race readiness, phase summary, plan adjust).
//     NEVER on rule-engine output, race projections, hand-authored copy.
//   - Working state pulses the sparkle and adds " · thinking" to the role line.
//   - Use 'warn' colour on --warn-bg surfaces (CoachNoteBlock, weekly report).
//     Default 'moss' everywhere else.
//   - When onClick is provided the byline becomes a tappable button (navigates
//     to Coach). Omit onClick on the Coach screen itself (already there).

import AIMark from './AIMark'
import { BRAND } from '@/lib/brand'

interface CoachBylineProps {
  /** Animated pulse — use while AI is generating. Adds "· thinking" to role line. */
  working?: boolean
  /**
   * Surface colour variant.
   * 'moss' (default) — for --card and --bg-soft surfaces.
   * 'warn' — for --warn-bg surfaces (CoachNoteBlock, weekly report card).
   */
  color?: 'moss' | 'warn'
  /**
   * Role line under the name. Defaults to "YOUR COACH". Override for context-
   * specific bylines like "MOVED YOUR TEMPO" on plan adjustments.
   */
  role?: string
  /**
   * When provided, the byline becomes interactive — tapping navigates to the
   * Coach tab. Omit on the Coach screen itself.
   */
  onClick?: () => void
  /** Tooltip shown on hover (desktop) and long-press (iOS). */
  title?: string
}

export default function CoachByline({
  working = false,
  color   = 'moss',
  role,
  onClick,
  title,
}: CoachBylineProps) {
  const isMoss      = color === 'moss'
  const accent      = isMoss ? 'var(--moss)' : 'var(--warn)'
  const avatarStart = isMoss ? 'var(--moss)' : 'var(--warn)'
  const avatarEnd   = isMoss ? '#5A7C5A'     : '#9A6F2A'
  const roleLabel   = role ?? 'YOUR COACH'
  const tooltip     = title ?? `${BRAND.coachName} is your AI coach`
  const initial     = BRAND.coachName.charAt(0).toUpperCase()

  const content = (
    <>
      {/* Avatar with anchored AIMark */}
      <span
        aria-hidden="true"
        style={{
          position:       'relative',
          width:          '22px',
          height:         '22px',
          borderRadius:   '50%',
          background:     `linear-gradient(135deg, ${avatarStart} 0%, ${avatarEnd} 100%)`,
          display:        'inline-flex',
          alignItems:     'center',
          justifyContent: 'center',
          color:          '#FFFFFF',
          fontFamily:     'var(--font-ui)',
          fontSize:       '11px',
          fontWeight:     700,
          letterSpacing:  '-0.02em',
          flexShrink:     0,
        }}
      >
        {initial}
        <span
          style={{
            position:     'absolute',
            bottom:       '-3px',
            right:        '-3px',
            background:   'var(--card)',
            borderRadius: '50%',
            padding:      '2px',
            display:      'inline-flex',
            lineHeight:   0,
          }}
        >
          <AIMark size={10} color={accent} working={working} />
        </span>
      </span>

      {/* Name + role */}
      <span
        style={{
          display:       'flex',
          flexDirection: 'column',
          lineHeight:    1.15,
          minWidth:      0,
        }}
      >
        <span
          style={{
            fontFamily:    'var(--font-ui)',
            fontSize:      '13px',
            fontWeight:    700,
            color:         'var(--ink)',
            letterSpacing: '-0.005em',
          }}
        >
          {BRAND.coachName}
        </span>
        <span
          style={{
            fontFamily:    'var(--font-ui)',
            fontSize:      '10px',
            fontWeight:    600,
            color:         accent,
            letterSpacing: '0.06em',
            textTransform: 'uppercase',
            opacity:       working ? 0.85 : 1,
          }}
        >
          {roleLabel}
          {working && (
            <span
              style={{
                marginLeft: '4px',
                opacity:    0.65,
                animation:  'coach-byline-thinking 1.6s ease-in-out infinite',
              }}
            >
              · thinking
            </span>
          )}
        </span>
      </span>
    </>
  )

  const sharedStyle: React.CSSProperties = {
    display:    'inline-flex',
    alignItems: 'center',
    gap:        '8px',
  }

  if (onClick) {
    return (
      <button
        type="button"
        onClick={onClick}
        title={tooltip}
        aria-label={`${BRAND.coachName} — ${roleLabel.toLowerCase()}`}
        style={{
          ...sharedStyle,
          background: 'transparent',
          border:     'none',
          padding:    0,
          cursor:     'pointer',
          textAlign:  'left',
        }}
      >
        {content}
      </button>
    )
  }

  return (
    <span
      role="img"
      aria-label={`${BRAND.coachName} — ${roleLabel.toLowerCase()}`}
      title={tooltip}
      style={sharedStyle}
    >
      {content}
    </span>
  )
}
