// coaching-review-round.ts — open a dated coaching-review round, both sets.
//
// The trigger for a PROACTIVE coaching review used to be "someone remembers"
// (README: "roughly monthly") and it went dormant. This script is the GENERATE
// step of that loop, modernised: it runs BOTH the 4 canonical cases
// (CANONICAL_CASES, from generate-coaching-review.ts) AND the 11 charity
// personas (CHARITY_PERSONAS), generates a real plan for each, runs validatePlan
// on it, writes a dated packet, and exits non-zero if any plan breaks its own
// constitution. The REVIEW step is the Coaching Board skill (/coaching-board),
// which supersedes the manual "senior coach" reviewer the folder was built around.
//
// It is wired to fire in CI whenever a coaching-doctrine file ships to main
// (.github/workflows/coaching-review-trigger.yml) — so a round is PROMPTED the
// moment doctrine changes, not when someone remembers.
//
// Run: NODE_ENV=production npx tsx scripts/coaching-review-round.ts

import fs from 'node:fs'
import { isDesignedRefusal } from '../lib/plan/designedRefusal'
import path from 'node:path'
import { generateRulePlan } from '../lib/plan/ruleEngine'
import { validatePlan } from '../lib/plan/invariants'
import { CANONICAL_CASES, renderCase, type Case } from './generate-coaching-review'
import { CHARITY_PERSONAS, charityInput, CHARITY_PLAN_START, type CharityPersona } from '../lib/plan/charityCohort'
import type { GeneratorInput } from '../types/plan'

const DATE = new Date().toISOString().slice(0, 10)
const outDir = path.resolve(__dirname, '..', 'coaching-review', DATE)

function charityToCase(p: CharityPersona): Case {
  return {
    id: p.id.split(/[ ,]/)[0].toLowerCase(),
    title: p.id,
    persona: `Charity cohort — ${p.note}`,
    tier: 'paid',
    input: { ...charityInput(p), plan_start: CHARITY_PLAN_START } as any,
    questions: [
      'Is this plan fit for a charity first-timer of this profile (low base, injury/masters as applicable)?',
      `Doctrine stressed: ${p.note}`,
    ],
  }
}

interface Row { id: string; distanceKm: number; errors: number; warns: number; status: string }

const rows: Row[] = []
const packets: string[] = []
let hardFail = false

function run(label: string, input: GeneratorInput, tier: 'free' | 'trial' | 'paid', planStart: string,
             renderAs: Case, expectRefusal = false) {
  try {
    const plan = generateRulePlan(input, tier, planStart)
    const v = validatePlan(plan, input)
    const errors = v.filter(x => x.severity === 'error')
    const warns = v.filter(x => x.severity === 'warn')
    if (expectRefusal) {
      // Expected a refusal, got a plan — the honesty guard weakened.
      hardFail = true
      rows.push({ id: label, distanceKm: input.race_distance_km, errors: errors.length, warns: warns.length, status: '⚠ expected refusal, generated' })
    } else {
      if (errors.length) hardFail = true
      rows.push({ id: label, distanceKm: input.race_distance_km, errors: errors.length, warns: warns.length, status: errors.length ? '❌ error' : '✅' })
    }
    packets.push(renderCase(renderAs, plan))
    if (errors.length) {
      packets.push('\n> **ERROR VIOLATIONS**\n' + errors.map(e => `> - [${e.code}] wk${e.week ?? '—'} ${e.message}`).join('\n') + '\n')
    }
  } catch (e: any) {
    const msg = String(e?.message ?? e).split('\n')[0]
    const refusal = isDesignedRefusal(e)   // REFUSAL-COPY-02 — type, not wording
    if (expectRefusal && refusal) {
      rows.push({ id: label, distanceKm: input.race_distance_km, errors: 0, warns: 0, status: '⛔ refused (by design)' })
    } else {
      hardFail = true
      rows.push({ id: label, distanceKm: input.race_distance_km, errors: 1, warns: 0, status: `💥 ${msg}` })
    }
    packets.push(`# ${renderAs.title}\n\n${refusal ? '⛔ BY-DESIGN REFUSAL' : '💥 THREW'}: ${msg}\n`)
  }
}

// Canonical cases (4)
for (const c of CANONICAL_CASES) {
  run(c.title, c.input as any, c.tier, (c.input as any).plan_start ?? '2026-04-27', c)
}
// Charity personas (11)
for (const p of CHARITY_PERSONAS) {
  run(p.id, charityInput(p), 'paid', CHARITY_PLAN_START, charityToCase(p), p.expectRefusal)
}

// ── Write the round ──────────────────────────────────────────────────────────
fs.mkdirSync(outDir, { recursive: true })

const summary = [
  `# Coaching review round — ${DATE}`,
  '',
  `Generated by \`scripts/coaching-review-round.ts\` (both sets: ${CANONICAL_CASES.length} canonical + ${CHARITY_PERSONAS.length} charity).`,
  '**REVIEW PENDING** — run \`/coaching-board\` over \`generated-plans.md\`, then fill this file with the ruling and open \`backlog.md\`.',
  '',
  '## Validation summary',
  '',
  '| Case | Distance | Errors | Warns | Status |',
  '|---|---|---|---|---|',
  ...rows.map(r => `| ${r.id} | ${r.distanceKm}km | ${r.errors} | ${r.warns} | ${r.status} |`),
  '',
  hardFail
    ? '> ❌ At least one plan errored or an honesty guard weakened — a doctrine change may have broken a case. Investigate before the board sits.'
    : '> ✅ Every case generated with 0 error violations, or refused by design. Warns are the board\'s to weigh.',
  '',
].join('\n')

fs.writeFileSync(path.join(outDir, 'generated-plans.md'), summary + '\n\n---\n\n' + packets.join('\n\n---\n\n'))
// Seed the review stub only if a human/board hasn't already written one.
const reviewPath = path.join(outDir, 'review.md')
if (!fs.existsSync(reviewPath)) fs.writeFileSync(reviewPath, summary)

console.log(summary)
console.log(`\nWrote ${outDir}/generated-plans.md`)
process.exit(hardFail ? 1 : 0)
