import { NextRequest, NextResponse } from 'next/server'
import { createClient as createServiceClient } from '@supabase/supabase-js'
import { getUserFromRequest } from '@/lib/supabase/getUserFromRequest'
import { getUserTier } from '@/lib/trial'
import { isFeatureAllowed } from '@/lib/plan/canUseFeature'

// POST /api/strava/unlink-activity
// Unlinks a Strava or Apple Health activity from a planned session.
// Clears strava_activity_id + apple_health_uuid from session_completions and
// deletes the run_analysis row for that session. strava_activities is left
// untouched — it is the activity record, not the session link.
//
// Auth: bearer token (paid/trial). Tier-gated on activity_intelligence.
// Body: { week_n: number, session_day: string }

export async function POST(req: NextRequest) {
  const user = await getUserFromRequest(req)
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const tier = await getUserTier(user.id)
  if (!isFeatureAllowed('activity_intelligence', tier)) {
    return NextResponse.json({ error: 'Subscription required' }, { status: 403 })
  }

  const body = await req.json()
  const { week_n, session_day } = body as { week_n: number; session_day: string }
  if (week_n == null || !session_day) {
    return NextResponse.json({ error: 'week_n and session_day required' }, { status: 422 })
  }

  const supabase = createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  // Clear the activity references from session_completions, preserving
  // all other fields (status, rpe, fatigue_tag, coaching_flag, etc.).
  const { error: completionErr } = await supabase
    .from('session_completions')
    .update({
      strava_activity_id:   null,
      apple_health_uuid:    null,
      strava_activity_name: null,
      strava_activity_km:   null,
      avg_hr:               null,
      updated_at:           new Date().toISOString(),
    })
    .eq('user_id', user.id)
    .eq('week_n', week_n)
    .eq('session_day', session_day)

  if (completionErr) {
    console.error('[unlink-activity] session_completions update failed', completionErr.message)
    return NextResponse.json({ error: 'Failed to unlink activity' }, { status: 500 })
  }

  // Delete the run_analysis rows for this session (both Strava and HealthKit
  // rows, if somehow both exist). Deleting is cleaner than soft-deleting —
  // the row can be regenerated by re-linking and re-analysing.
  const { error: analysisErr } = await supabase
    .from('run_analysis')
    .delete()
    .eq('user_id', user.id)
    .eq('week_n', week_n)
    .eq('session_day', session_day)

  if (analysisErr) {
    console.error('[unlink-activity] run_analysis delete failed', analysisErr.message)
    // Non-fatal — completion was already cleared. Log and continue.
  }

  return NextResponse.json({ ok: true })
}
