import { describe, it, expect } from 'vitest'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { isDeloadWeek, computeDeloadWeeks } from './deloadCadence'
import type { GeneratorPhase } from '@/types/plan'

/**
 * DELOAD-OWNER-01 — the deload cadence has exactly one owner.
 *
 * The consolidation itself was proved by measurement, not by these tests: 432
 * plans (6 distances x 3 day-counts x 2 ages x 3 declared levels x 2 goals x 2
 * injury histories) generated byte-identically before and after. The age axis
 * matters — it flips the masters branch that sets `recoveryFreq`, so the cadence
 * path is genuinely exercised rather than held constant.
 *
 * What these tests defend is the thing that actually failed: RE-duplication.
 * Five copies existed and agreed only by accident of surrounding control flow,
 * so changing two of them made the volume curve and the week badge disagree.
 * A refactor that removes copies without preventing new ones has bought nothing
 * — the next person adds a sixth.
 */

describe('isDeloadWeek — the predicate', () => {
  it('fires on the cadence in base and build', () => {
    expect(isDeloadWeek(4, 'base', 4)).toBe(true)
    expect(isDeloadWeek(8, 'build', 4)).toBe(true)
    expect(isDeloadWeek(3, 'base', 4)).toBe(false)
    expect(isDeloadWeek(9, 'build', 4)).toBe(false)
  })

  it('never fires in peak or taper', () => {
    // Peak is where the plan is meant to be hardest; taper is already a planned
    // drop, so a deload inside one is a second drop or a contradiction.
    expect(isDeloadWeek(4, 'peak', 4)).toBe(false)
    expect(isDeloadWeek(8, 'taper', 4)).toBe(false)
  })

  it('honours the masters cadence (§3)', () => {
    // 3:1 for masters vs 4:1 otherwise — the two must not be assumed equal.
    expect(isDeloadWeek(3, 'build', 3)).toBe(true)
    expect(isDeloadWeek(3, 'build', 4)).toBe(false)
    expect(isDeloadWeek(4, 'build', 3)).toBe(false)
  })

  it('refuses a nonsensical frequency instead of making every week a deload', () => {
    // `x % 0` is NaN and `NaN === 0` is false, so a zero would have read as
    // "never a deload" — but a negative or fractional frequency would produce
    // arbitrary answers. This app's bugs are silent, so the guard is explicit.
    expect(isDeloadWeek(4, 'build', 0)).toBe(false)
    expect(isDeloadWeek(4, 'build', -1)).toBe(false)
    expect(isDeloadWeek(4, 'build', Number.NaN)).toBe(false)
    expect(isDeloadWeek(0, 'build', 4)).toBe(false)
  })

  it('does NOT exclude race week — that is the caller’s question', () => {
    // "Is week N on the cadence" and "should this week be badged a deload" are
    // different questions. Only the second cares that the race is on Saturday,
    // and only the badge site asks it.
    expect(isDeloadWeek(12, 'build', 4)).toBe(true)
  })
})

describe('DELOAD-OWNER-01 — single ownership is mechanical, not remembered', () => {
  const LIB = join(process.cwd(), 'lib')
  const OWNER = 'deloadCadence.ts'

  const tsFiles = (dir: string): string[] =>
    readdirSync(dir).flatMap(name => {
      const full = join(dir, name)
      if (statSync(full).isDirectory()) return tsFiles(full)
      return name.endsWith('.ts') && !name.endsWith('.test.ts') ? [full] : []
    })

  it('no file outside the owner computes the cadence itself', () => {
    // Targeted at the exact expression that was copied five times. It cannot
    // catch a copy that renames the variable — stated rather than pretended
    // away — but it does catch the overwhelmingly likely case: someone reaching
    // for the same idiom in the same file where it used to live.
    // `invariants.ts` is allowed to recompute the cadence, and MUST be. A
    // checker that imports the producer's own predicate cannot catch the
    // producer being wrong about it — the same reason `rowHasMixedWorkAnchors`
    // is deliberately duplicated there. The rule is one owner among PRODUCERS,
    // not one expression in the repo.
    const CHECKER = 'invariants.ts'
    const offenders: string[] = []
    for (const file of tsFiles(LIB)) {
      if (file.endsWith(OWNER) || file.endsWith(CHECKER)) continue
      const src = readFileSync(file, 'utf8')
      if (/%\s*recoveryFreq/.test(src)) offenders.push(file.replace(process.cwd() + '/', ''))
    }
    expect(
      offenders,
      `These files compute the deload cadence themselves. Import isDeloadWeek from ` +
      `lib/plan/deloadCadence.ts instead — five copies of this expression drifted ` +
      `apart once already (DELOAD-OWNER-01) and the disagreement was invisible.`,
    ).toEqual([])
  })

  it('the owner is actually used — this is not a dead module', () => {
    // A single owner nothing imports is worse than five copies: it reads as
    // solved. Guards the case where a future edit inlines the logic back and
    // leaves the module orphaned, which the check above would not notice.
    const importers = tsFiles(LIB).filter(f =>
      !f.endsWith(OWNER) && /from '\.\/deloadCadence'|from '@\/lib\/plan\/deloadCadence'/.test(readFileSync(f, 'utf8')),
    )
    expect(importers.length, 'nothing imports deloadCadence — the owner has been orphaned').toBeGreaterThan(0)
  })

  it('every call site in the engine goes through the owner', () => {
    // The engine held all five copies. Pin the count so a sixth call site is a
    // deliberate act rather than a silent addition.
    // Updated by CB-DELOAD-01: the engine no longer calls the raw predicate at
    // all. Placement is computed ONCE by `computeDeloadWeeks` and every site
    // reads that set — which is a stronger form of the same ownership, since
    // even the predicate cannot now be applied inconsistently per site.
    const engine = readFileSync(join(LIB, 'plan', 'ruleEngine.ts'), 'utf8')
    // 5 -> 6 on 2026-09-07 (§97). The sixth read is `vo2BuildSlotIndex`, which
    // walks the build weeks to find the first one clear of an intensity re-entry
    // window and must skip deload weeks (they carry no quality). It reads the
    // OWNER's computed set, which is exactly what this test exists to require —
    // the count is a proxy for "nobody recomputed the cadence", not a ceiling on
    // legitimate consumers.
    const setReads = engine.match(/deloadWeeks\.has\(/g) ?? []
    expect(setReads.length, 'every cadence decision should read the one computed set').toBe(6)
    const computes = engine.match(/computeDeloadWeeks\(/g) ?? []
    expect(computes.length, 'placement must be computed exactly once per plan').toBe(1)
  })
})

describe('§95 — a deload must not sit at phase position 2 either', () => {
  /** base 1..baseEnd, build baseEnd+1..buildEnd, peak, then taper. */
  const phases = (baseEnd: number, buildEnd: number, peakEnd: number) =>
    (n: number): GeneratorPhase =>
      n <= baseEnd ? 'base' : n <= buildEnd ? 'build' : n <= peakEnd ? 'peak' : 'taper'

  const adjacent = (ws: number[]) => ws.some((w, i) => i > 0 && w - ws[i - 1] === 1)
  const sorted = (s: Set<number>) => Array.from(s).sort((a, b) => a - b)

  it('MASTERS (freq 3): never places adjacent deloads — the reverted build did', () => {
    // THE REGRESSION THIS PINS. The first implementation guarded on
    // `since === recoveryFreq - 3`, which for the masters cadence of 3
    // DEGENERATES TO `since === 0` — true on the very week after a placement.
    // It produced [3,6] -> [3,4,7]: back-to-back recovery weeks, count inflated,
    // peak crushed, 453 plans flipped to a do-nothing maintenance plan.
    for (const total of [8, 9, 10, 11, 12, 14, 16, 18]) {
      const baseEnd = Math.max(2, Math.round(total * 0.35))
      const buildEnd = Math.max(baseEnd + 1, Math.round(total * 0.72))
      const pf = phases(baseEnd, buildEnd, Math.max(buildEnd + 1, total - 2))
      const weeks = sorted(computeDeloadWeeks(total, 3, pf))
      expect(adjacent(weeks), `masters ${total}w produced adjacent deloads: [${weeks}]`).toBe(false)
    }
  })

  it('STANDARD (freq 4): clears position 2 and keeps the count', () => {
    const pf = phases(6, 12, 14)
    const before = sorted(computeDeloadWeeks(16, 4, pf, false))
    const after = sorted(computeDeloadWeeks(16, 4, pf, true))
    expect(before).toEqual([4, 8, 12])
    expect(after).toEqual([2, 6, 10])
    expect(after.length).toBe(before.length)   // Willy: count may rise, never fall
    expect(adjacent(after)).toBe(false)
  })

  it('avoidPosition2=false reverts to §87 placement exactly — the §1 yield path', () => {
    // §95 Amendment 1: when the preference breaches a ceiling the plan falls
    // back here, so this must be byte-identical to pre-§95 behaviour.
    for (const freq of [3, 4]) {
      for (const total of [10, 12, 16, 20]) {
        const pf = phases(Math.round(total * 0.35), Math.round(total * 0.72), total - 2)
        const reverted = sorted(computeDeloadWeeks(total, freq, pf, false))
        expect(adjacent(reverted)).toBe(false)
        expect(reverted.length).toBeGreaterThan(0)
      }
    }
  })

  it('never lengthens the worst loading run (Sims, §87 rule 3)', () => {
    const worstRun = (ws: number[], total: number, pf: (n: number) => GeneratorPhase) => {
      let worst = 0, run = 0
      for (let n = 1; n <= total; n++) {
        const p = pf(n)
        if (p === 'peak' || p === 'taper') continue
        if (ws.includes(n)) { worst = Math.max(worst, run); run = 0 } else run++
      }
      return Math.max(worst, run)
    }
    for (const freq of [3, 4]) {
      for (const total of [10, 12, 14, 16, 18, 20]) {
        const pf = phases(Math.round(total * 0.35), Math.round(total * 0.72), total - 2)
        const before = sorted(computeDeloadWeeks(total, freq, pf, false))
        const after = sorted(computeDeloadWeeks(total, freq, pf, true))
        expect(
          worstRun(after, total, pf),
          `freq ${freq}, ${total}w: [${before}] -> [${after}] lengthened the loading run`,
        ).toBeLessThanOrEqual(worstRun(before, total, pf))
      }
    }
  })
})
